# Site settings
title: A Conta dos Passaralhos
tag_text: A Conta dos Passaralhos
description: Um panorama sobre demissões de jornalistas nas redações do Brasil desde 2012.
jornalistas: 2.123
total: 7.277
atualizacao: 19/04/2017

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
